In [1]:
import pandas as pd

In [3]:
train_df = pd.read_csv("favorita-grocery-sales-forecasting/train.csv")
holidays_events_df = pd.read_csv("favorita-grocery-sales-forecasting/holidays_events.csv")
items_df = pd.read_csv("favorita-grocery-sales-forecasting/items.csv")
oil_df = pd.read_csv("favorita-grocery-sales-forecasting/oil.csv")
stores_df = pd.read_csv("favorita-grocery-sales-forecasting/stores.csv")
transactions_df = pd.read_csv("favorita-grocery-sales-forecasting/transactions.csv")

/var/folders/5l/17wd4myj387b056cpgkkpxth0000gn/T/ipykernel_96989/835144111.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv("favorita-grocery-sales-forecasting/train.csv")

In [4]:
train_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125497040 entries, 0 to 125497039
Data columns (total 6 columns):
 #   Column       Non-Null Count      Dtype
---  ------       --------------      -----
 0   id           125497040 non-null  int64
 1   date         125497040 non-null  object
 2   store_nbr    125497040 non-null  int64
 3   item_nbr     125497040 non-null  int64
 4   unit_sales   125497040 non-null  float64
 5   onpromotion  103839389 non-null  object
dtypes: float64(1), int64(3), object(2)
memory usage: 5.6+ GB

In [5]:
holidays_events_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    object
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), object(5)
memory usage: 14.1+ KB

In [6]:
items_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4100 entries, 0 to 4099
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item_nbr    4100 non-null   int64
 1   family      4100 non-null   object
 2   class       4100 non-null   int64
 3   perishable  4100 non-null   int64
dtypes: int64(3), object(1)
memory usage: 128.3+ KB

In [7]:
oil_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [8]:
stores_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB

In [9]:
transactions_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

Merging

In [10]:
df = train_df.copy()

In [11]:
df = df.merge(items_df, on='item_nbr', how='left')
df.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,family,class,perishable
0,0,2013-01-01,25,103665,7.0,NaN,BREAD/BAKERY,2712,1
1,1,2013-01-01,25,105574,1.0,NaN,GROCERY I,1045,0
2,2,2013-01-01,25,105575,2.0,NaN,GROCERY I,1045,0
3,3,2013-01-01,25,108079,1.0,NaN,GROCERY I,1030,0
4,4,2013-01-01,25,108701,1.0,NaN,DELI,2644,1

In [12]:
df = df.merge(stores_df, on='store_nbr', how='left')
df.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,family,class,perishable,city,state,type,cluster
0,0,2013-01-01,25,103665,7.0,NaN,BREAD/BAKERY,2712,1,Salinas,Santa Elena,D,1
1,1,2013-01-01,25,105574,1.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1
2,2,2013-01-01,25,105575,2.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1
3,3,2013-01-01,25,108079,1.0,NaN,GROCERY I,1030,0,Salinas,Santa Elena,D,1
4,4,2013-01-01,25,108701,1.0,NaN,DELI,2644,1,Salinas,Santa Elena,D,1

In [13]:
df = df.merge(oil_df, on="date", how="left")
df["dcoilwtico"] = df["dcoilwtico"].ffill()
df.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,family,class,perishable,city,state,type,cluster,dcoilwtico
0,0,2013-01-01,25,103665,7.0,NaN,BREAD/BAKERY,2712,1,Salinas,Santa Elena,D,1,NaN
1,1,2013-01-01,25,105574,1.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1,NaN
2,2,2013-01-01,25,105575,2.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1,NaN
3,3,2013-01-01,25,108079,1.0,NaN,GROCERY I,1030,0,Salinas,Santa Elena,D,1,NaN
4,4,2013-01-01,25,108701,1.0,NaN,DELI,2644,1,Salinas,Santa Elena,D,1,NaN

In [14]:
df = df.merge(transactions_df, on=["date", "store_nbr"], how="left")
df.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,family,class,perishable,city,state,type,cluster,dcoilwtico,transactions
0,0,2013-01-01,25,103665,7.0,NaN,BREAD/BAKERY,2712,1,Salinas,Santa Elena,D,1,NaN,770.0
1,1,2013-01-01,25,105574,1.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1,NaN,770.0
2,2,2013-01-01,25,105575,2.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1,NaN,770.0
3,3,2013-01-01,25,108079,1.0,NaN,GROCERY I,1030,0,Salinas,Santa Elena,D,1,NaN,770.0
4,4,2013-01-01,25,108701,1.0,NaN,DELI,2644,1,Salinas,Santa Elena,D,1,NaN,770.0

In [15]:
holidays_events_df

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

In [16]:
holidays_events_df = holidays_events_df[holidays_events_df['transferred'] == False]
holidays_events_df

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

In [17]:
holidays_events_df = holidays_events_df.groupby("date").agg({
    "type": "first",
    "locale": "first"
}).reset_index()
holidays_events_df["is_holiday"] = 1
holidays_events_df

           date        type    locale  is_holiday
0    2012-03-02     Holiday     Local           1
1    2012-04-01     Holiday  Regional           1
2    2012-04-12     Holiday     Local           1
3    2012-04-14     Holiday     Local           1
4    2012-04-21     Holiday     Local           1
..          ...         ...       ...         ...
295  2017-12-22     Holiday     Local           1
296  2017-12-23  Additional  National           1
297  2017-12-24  Additional  National           1
298  2017-12-25     Holiday  National           1
299  2017-12-26  Additional  National           1

[300 rows x 4 columns]

In [18]:
df = df.merge(holidays_events_df[["date", "is_holiday"]], on='date', how='left')
df["is_holiday"] = df["is_holiday"].fillna(0)
df.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,family,class,perishable,city,state,type,cluster,dcoilwtico,transactions,is_holiday
0,0,2013-01-01,25,103665,7.0,NaN,BREAD/BAKERY,2712,1,Salinas,Santa Elena,D,1,NaN,770.0,1.0
1,1,2013-01-01,25,105574,1.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1,NaN,770.0,1.0
2,2,2013-01-01,25,105575,2.0,NaN,GROCERY I,1045,0,Salinas,Santa Elena,D,1,NaN,770.0,1.0
3,3,2013-01-01,25,108079,1.0,NaN,GROCERY I,1030,0,Salinas,Santa Elena,D,1,NaN,770.0,1.0
4,4,2013-01-01,25,108701,1.0,NaN,DELI,2644,1,Salinas,Santa Elena,D,1,NaN,770.0,1.0

In [19]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125497040 entries, 0 to 125497039
Data columns (total 16 columns):
 #   Column        Non-Null Count      Dtype
---  ------        --------------      -----
 0   id            125497040 non-null  int64
 1   date          125497040 non-null  object
 2   store_nbr     125497040 non-null  int64
 3   item_nbr      125497040 non-null  int64
 4   unit_sales    125497040 non-null  float64
 5   onpromotion   103839389 non-null  object
 6   family        125497040 non-null  object
 7   class         125497040 non-null  int64
 8   perishable    125497040 non-null  int64
 9   city          125497040 non-null  object
 10  state         125497040 non-null  object
 11  type          125497040 non-null  object
 12  cluster       125497040 non-null  int64
 13  dcoilwtico    125496462 non-null  float64
 14  transactions  125282415 non-null  float64
 15  is_holiday    125497040 non-null  float64
dtypes: float64(4), int64(6), object(6)
memory usage: 15.0+ GB

In [20]:
cols_to_keep = [
    "date",
    "store_nbr",
    "item_nbr",
    "unit_sales",
    "cluster",
    "state",
    "is_holiday"
]

df = df[cols_to_keep]

In [21]:
df["date"] = pd.to_datetime(df["date"])
print(df["date"].min())
print(df["date"].max())

2013-01-01 00:00:00
2017-08-15 00:00:00

In [22]:
df = df[df["date"] >= '2017-01-01']
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 23808261 entries, 101688779 to 125497039
Data columns (total 7 columns):
 #   Column      Non-Null Count     Dtype
---  ------      --------------     -----
 0   date        23808261 non-null  datetime64[ns]
 1   store_nbr   23808261 non-null  int64
 2   item_nbr    23808261 non-null  int64
 3   unit_sales  23808261 non-null  float64
 4   cluster     23808261 non-null  int64
 5   state       23808261 non-null  object
 6   is_holiday  23808261 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 1.4+ GB

In [23]:
df.head()

,date,store_nbr,item_nbr,unit_sales,cluster,state,is_holiday
101688779,2017-01-01,25,99197,1.0,1,Santa Elena,0.0
101688780,2017-01-01,25,103665,7.0,1,Santa Elena,0.0
101688781,2017-01-01,25,105574,1.0,1,Santa Elena,0.0
101688782,2017-01-01,25,105857,4.0,1,Santa Elena,0.0
101688783,2017-01-01,25,106716,2.0,1,Santa Elena,0.0

In [25]:
df = df.reset_index(drop=True)
df.head()

,index,date,store_nbr,item_nbr,unit_sales,cluster,state,is_holiday
0,101688779,2017-01-01,25,99197,1.0,1,Santa Elena,0.0
1,101688780,2017-01-01,25,103665,7.0,1,Santa Elena,0.0
2,101688781,2017-01-01,25,105574,1.0,1,Santa Elena,0.0
3,101688782,2017-01-01,25,105857,4.0,1,Santa Elena,0.0
4,101688783,2017-01-01,25,106716,2.0,1,Santa Elena,0.0

In [26]:
df = df.drop(columns=["index"])
df.head()

,date,store_nbr,item_nbr,unit_sales,cluster,state,is_holiday
0,2017-01-01,25,99197,1.0,1,Santa Elena,0.0
1,2017-01-01,25,103665,7.0,1,Santa Elena,0.0
2,2017-01-01,25,105574,1.0,1,Santa Elena,0.0
3,2017-01-01,25,105857,4.0,1,Santa Elena,0.0
4,2017-01-01,25,106716,2.0,1,Santa Elena,0.0

In [27]:
df = df[df["date"] <= '2017-6-30']
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 18954132 entries, 0 to 18954131
Data columns (total 7 columns):
 #   Column      Non-Null Count     Dtype
---  ------      --------------     -----
 0   date        18954132 non-null  datetime64[ns]
 1   store_nbr   18954132 non-null  int64
 2   item_nbr    18954132 non-null  int64
 3   unit_sales  18954132 non-null  float64
 4   cluster     18954132 non-null  int64
 5   state       18954132 non-null  object
 6   is_holiday  18954132 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 1.1+ GB

In [28]:
df["item_nbr"].nunique()

3971

In [29]:
df["store_nbr"].nunique()

54

In [30]:
combo_counts = (
    df.groupby(["store_nbr", "item_nbr"], as_index=False)
    .size()
    .rename(columns={"size": "record_count"})
    .sort_values("record_count", ascending=False)
)

print(combo_counts.describe())
print(f"\nTotal unique combinations: {len(combo_counts):,}")
print(f"Expected max records per combo: {df['date'].nunique()}")

           store_nbr      item_nbr   record_count
count  165448.000000  1.654480e+05  165448.000000
mean       27.907264  1.210858e+06     114.562473
std        15.999129  5.812853e+05      54.494101
min         1.000000  9.699500e+04       1.000000
25%        14.000000  7.817940e+05      70.000000
50%        28.000000  1.239858e+06     128.000000
75%        42.000000  1.693652e+06     164.000000
max        54.000000  2.113914e+06     181.000000

Total unique combinations: 165,448
Expected max records per combo: 181

In [31]:
small_df = df[df["store_nbr"].isin([1, 2, 3])]
print(f"Rows: {len(small_df):,}")
print(f"Stores: {small_df['store_nbr'].unique()}")
print(f"Memory: {small_df.memory_usage(deep=True).sum() / 1024**2:.1f} MB")

Rows: 1,266,153
Stores: [1 2 3]
Memory: 137.7 MB

In [34]:
daily_sales = df.groupby('date').agg(
    unit_sales=('unit_sales', 'sum'),
    item_count=('item_nbr', 'nunique')
).reset_index()
daily_sales

          date   unit_sales  item_count
0   2017-01-01    12082.501        1693
1   2017-01-02  1402305.371        3800
2   2017-01-03  1104377.080        3800
3   2017-01-04   990093.463        3790
4   2017-01-05   777620.954        3790
..         ...          ...         ...
176 2017-06-26   755367.845        3767
177 2017-06-27   682218.469        3765
178 2017-06-28   731896.985        3763
179 2017-06-29   630811.803        3755
180 2017-06-30   802273.139        3766

[181 rows x 3 columns]

In [35]:
daily_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        181 non-null    datetime64[ns]
 1   unit_sales  181 non-null    float64
 2   item_count  181 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 4.4 KB

In [36]:
small_df.to_parquet("datasets/sample_dataset_6m.parquet", index=False)